In [1]:
# Install required packages (run in Colab or your environment)
!pip install -qqq "transformers>=4.55.0" "trl>=0.22.1" "datasets" "torch"
!pip install -qqq "accelerate" "peft" "trackio" "huggingface_hub"

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 532.9/532.9 kB 37.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 63.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.2/24.2 MB 103.6 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.7/55.7 kB 5.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 156.3 MB/s eta 0:00:00a 0:00:01

In [2]:
import transformers, trl, datasets, torch
print(transformers.__version__, trl.__version__, datasets.__version__, torch.__version__)

4.57.6 0.27.1 4.0.0 2.9.0+cu126

In [3]:
# Import necessary libraries
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
from datasets import load_dataset

if torch.cuda.is_available():
    device = "cuda"
    print(f"Using CUDA GPU: {torch.cuda.get_device_name()}")
    print(f"GPU memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f}GB")
elif hasattr(torch.backends, "mps") and torch.backends.mps.is_available():
    device = "mps"
    print("Using Apple MPS")
else:
    device = "cpu"
    print("Using CPU - you will need to use a GPU to train models")

# Authenticate with Hugging Face (optional, for private models)
from huggingface_hub import login
login()  # Uncomment if you need to access private models

Using CUDA GPU: NVIDIA A100-SXM4-80GB
GPU memory: 85.2GB

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

### Load SmolLM3 Models

Now let's load the base and instruct models for comparison.

In [4]:
# Load both base and instruct models for comparison
base_model_name = "HuggingFaceTB/SmolLM3-3B-Base"
instruct_model_name = "HuggingFaceTB/SmolLM3-3B"

# Load tokenizers
base_tokenizer = AutoTokenizer.from_pretrained(base_model_name)
instruct_tokenizer = AutoTokenizer.from_pretrained(instruct_model_name)

# Load models (use smaller precision for memory efficiency)
# Load base model
base_model = AutoModelForCausalLM.from_pretrained(
    base_model_name, dtype=torch.float16, device_map="auto"
)

# Load instruct model
instruct_model = AutoModelForCausalLM.from_pretrained(
    instruct_model_name, dtype=torch.float16, device_map="auto"
)

print("Models loaded successfully!")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:104: UserWarning:
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
You are not authenticated with the Hugging Face Hub in this notebook.
If the error persists, please let us know by opening an issue on GitHub (https://github.com/huggingface/huggingface_hub/issues/new).
  warnings.warn(

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json:   0%|          | 0.00/17.2M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/151 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json:   0%|          | 0.00/17.2M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/289 [00:00<?, ?B/s]

chat_template.jinja: 0.00B [00:00, ?B/s]

config.json:   0%|          | 0.00/943 [00:00<?, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/1.18G [00:00<?, ?B/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/4.97G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/126 [00:00<?, ?B/s]

config.json: 0.00B [00:00, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/1.18G [00:00<?, ?B/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/4.97G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/182 [00:00<?, ?B/s]

Models loaded successfully!

### Compare Base vs Instruct Model Responses

In [5]:
# Test the same prompt on both models
test_prompt = "Explain quantum computing in simple terms."

# Prepare the prompt for base model (no chat template)
base_inputs = base_tokenizer(test_prompt, return_tensors="pt").to(device)

# Prepare the prompt for instruct model (with chat template)
instruct_messages = [
    {"role": "system", "content": "/no_think"},
    {"role": "user", "content": test_prompt}
]
instruct_formatted = instruct_tokenizer.apply_chat_template(
    instruct_messages, tokenize=False, add_generation_prompt=True
)
instruct_inputs = instruct_tokenizer(instruct_formatted, return_tensors="pt").to(device)

# Generate responses
print("=== Model comparison ===\n")

print("🤖 BASE MODEL RESPONSE:")
with torch.no_grad():
    base_outputs = base_model.generate(
        **base_inputs,
        max_new_tokens=150,
        temperature=0.7,
        do_sample=True,
        pad_token_id=base_tokenizer.eos_token_id,
    )
    base_response = base_tokenizer.decode(base_outputs[0], skip_special_tokens=True)
    print(base_response[len(test_prompt):])  # Show only the generated part

print("\n" + "=" * 50)
print("Instruct model response:")
with torch.no_grad():
    # # TODO Begin 
    # # Generate response from instruct model (20 points)
    # # instruct_outputs = instruct_model.generate(...)
    # # TODO End
    instruct_outputs = instruct_model.generate(
        **instruct_inputs,
        max_new_tokens=150,
        temperature=0.7,
        do_sample=True,
        pad_token_id=instruct_tokenizer.eos_token_id,
    )
    instruct_response = instruct_tokenizer.decode(
        instruct_outputs[0], skip_special_tokens=False # Note: specical tokens such as <|im_start|>
    )
    # Extract only the assistant's response
    assistant_start = instruct_response.find("<|im_start|>assistant\n") + len(
        "<|im_start|>assistant\n"
    )
    assistant_response = instruct_response[assistant_start::].split("<|im_end|>")[0]
    print(assistant_response)

=== Model comparison ===

🤖 BASE MODEL RESPONSE:


1 Answer

giorgiana1976's profile pic

giorgiana1976 | College Teacher | (Level 3) Valedictorian

Posted on

Quantum computing is a new branch of computer science, which is based on quantum theory.

Quantum theory is the branch of physics, which studies the physical properties of physical systems, which are smaller than the atomic scale.

We know that the smallest physical system is the atom, which has a nucleus at it's center and electrons rotating around the nucleus. Quantum computing uses not the classical computers, but the quantum computers, which are based on the properties of the quantum physics.

Quantum computers are more powerful than classical computers because they are based on superposition principle and entanglement

==================================================
Instruct model response:
<think>

</think>
Quantum computing is a type of computing that uses the principles of quantum mechanics to perform calculations. In classical computing, a bit is a basic unit of information that can be either 0 or 1. However, in quantum computing, we use quantum bits, or qubits, which can be in a state of 0, 1, or both at the same time, thanks to a property called superposition.

Think of it like a coin that can be both heads and tails at the same time, until you look at it. If you flip the coin, you can't know the result until you observe it. Similarly, a qubit can exist in multiple states simultaneously until you measure it.

Another key property of qubits is entang

### Customizing Data into Chat-Format and the GSM8K Dataset Example

In [6]:
# Function to process different dataset formats
def process_qa_dataset(examples, question_col, answer_col):
    """Process Q&A datasets into chat format"""
    processed = []

    for question, answer in zip(examples[question_col], examples[answer_col]):
        messages = [
            {"role": "user", "content": question},
            {"role": "assistant", "content": answer},
        ]
        processed.append(messages)

    return {"messages": processed}


def process_instruction_dataset(examples):
    """Process instruction-following datasets"""
    processed = []

    for instruction, response in zip(examples["instruction"], examples["response"]):
        messages = [
            {"role": "user", "content": instruction},
            {"role": "assistant", "content": response},
        ]
        processed.append(messages)

    return {"messages": processed}


# Example: Process GSM8K math dataset
print("=== PROCESSING GSM8K DATASET ===\n")

gsm8k = load_dataset(
    "openai/gsm8k", "main", split="train[:100]"
)  # Small subset for demo
print(f"Original GSM8K example: {gsm8k[0]}")

print("\n" + "=" * 50)

# Convert to chat format
def process_gsm8k(examples):
    processed = []
    for question, answer in zip(examples["question"], examples["answer"]):
        messages = [
            {
                "role": "system",
                "content": "You are a math tutor. Solve problems step by step.",
            },
            {"role": "user", "content": question},
            {"role": "assistant", "content": answer},
        ]
        processed.append(messages)
    return {"messages": processed}


gsm8k_processed = gsm8k.map(
    process_gsm8k, batched=True, remove_columns=gsm8k.column_names
)
print(f"Processed example: {gsm8k_processed[0]}")

=== PROCESSING GSM8K DATASET ===

README.md: 0.00B [00:00, ?B/s]

main/train-00000-of-00001.parquet:   0%|          | 0.00/2.31M [00:00<?, ?B/s]

main/test-00000-of-00001.parquet:   0%|          | 0.00/419k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/7473 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/1319 [00:00<?, ? examples/s]

Original GSM8K example: {'question': 'Natalia sold clips to 48 of her friends in April, and then she sold half as many clips in May. How many clips did Natalia sell altogether in April and May?', 'answer': 'Natalia sold 48/2 = <<48/2=24>>24 clips in May.\nNatalia sold 48+24 = <<48+24=72>>72 clips altogether in April and May.\n#### 72'}

==================================================

Map:   0%|          | 0/100 [00:00<?, ? examples/s]

Processed example: {'messages': [{'content': 'You are a math tutor. Solve problems step by step.', 'role': 'system'}, {'content': 'Natalia sold clips to 48 of her friends in April, and then she sold half as many clips in May. How many clips did Natalia sell altogether in April and May?', 'role': 'user'}, {'content': 'Natalia sold 48/2 = <<48/2=24>>24 clips in May.\nNatalia sold 48+24 = <<48+24=72>>72 clips altogether in April and May.\n#### 72', 'role': 'assistant'}]}

### Applying Chat Template to the Processed Chat-formatted Dataset

In [7]:
# Function to apply chat templates to processed datasets
def apply_chat_template_to_dataset(dataset, tokenizer):
    """Apply chat template to dataset for training"""

    def format_messages(examples):
        formatted_texts = []

        for messages in examples["messages"]:
            # # TODO Begin
            # # Apply chat template (20 points)
            # # HINT: Use tokenizer.apply_chat_template
            # # formatted_text = ...
            # # formatted_texts.append(formatted_text)
            # # TODO End
            formatted_text = tokenizer.apply_chat_template(
                messages,
                tokenize=False,
                add_generation_prompt=False,  # We want the complete conversation for fine-tuning instead of inference
            )
            formatted_texts.append(formatted_text)
        return {"text": formatted_texts}

    return dataset.map(format_messages, batched=True)


# Apply to our processed GSM8K dataset
gsm8k_formatted = apply_chat_template_to_dataset(gsm8k_processed, instruct_tokenizer)
print("=== FORMATTED TRAINING DATA ===")
print(gsm8k_formatted[0]["text"])

Map:   0%|          | 0/100 [00:00<?, ? examples/s]

=== FORMATTED TRAINING DATA ===
<|im_start|>system
## Metadata

Knowledge Cutoff Date: June 2025
Today Date: 01 February 2026
Reasoning Mode: /think

## Custom Instructions

You are a math tutor. Solve problems step by step.

<|im_start|>user
Natalia sold clips to 48 of her friends in April, and then she sold half as many clips in May. How many clips did Natalia sell altogether in April and May?<|im_end|>
<|im_start|>assistant
Natalia sold 48/2 = <<48/2=24>>24 clips in May.
Natalia sold 48+24 = <<48+24=72>>72 clips altogether in April and May.
#### 72<|im_end|>

### SmolTalk2 Dataset Inspection and Preparation

In [8]:
from datasets import load_dataset

# Load and prepare training dataset
print("=== PREPARING DATASET ===\n")

# Use SmolTalk2
dataset_dict = load_dataset("HuggingFaceTB/smoltalk2", "SFT")
print(f"Total splits: {len(dataset_dict)}")
print(f"Available splits: {list(dataset_dict.keys())}")
print(f"Number of total rows: {sum([dataset_dict[d].num_rows for d in dataset_dict])}")
print(f"Dataset structure: {dataset_dict}")

training_split = "smoltalk_everyday_convs_reasoning_Qwen3_32B_think"
print("NUmber of rows in this training split: ", len(dataset_dict[training_split]))

train_dataset = dataset_dict[training_split].select(range(2000))  # Use subset for faster training

=== PREPARING DATASET ===

README.md: 0.00B [00:00, ?B/s]

Resolving data files:   0%|          | 0/124 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/113 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/113 [00:00<?, ?it/s]

SFT/LongAlign_64k_Qwen3_32B_yarn_131k_th(…):   0%|          | 0.00/135M [00:00<?, ?B/s]

SFT/LongAlign_64k_Qwen3_32B_yarn_131k_th(…):   0%|          | 0.00/134M [00:00<?, ?B/s]

Downloading data:   0%|          | 0/113 [00:00<?, ?files/s]

SFT/OpenThoughts3_1.2M_think-00000-of-00(…):   0%|          | 0.00/287M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00001-of-00(…):   0%|          | 0.00/287M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00002-of-00(…):   0%|          | 0.00/288M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00003-of-00(…):   0%|          | 0.00/287M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00004-of-00(…):   0%|          | 0.00/287M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00005-of-00(…):   0%|          | 0.00/287M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00006-of-00(…):   0%|          | 0.00/287M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00007-of-00(…):   0%|          | 0.00/287M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00008-of-00(…):   0%|          | 0.00/288M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00009-of-00(…):   0%|          | 0.00/287M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00010-of-00(…):   0%|          | 0.00/287M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00011-of-00(…):   0%|          | 0.00/287M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00012-of-00(…):   0%|          | 0.00/286M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00013-of-00(…):   0%|          | 0.00/287M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00014-of-00(…):   0%|          | 0.00/287M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00015-of-00(…):   0%|          | 0.00/287M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00016-of-00(…):   0%|          | 0.00/287M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00017-of-00(…):   0%|          | 0.00/287M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00018-of-00(…):   0%|          | 0.00/287M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00019-of-00(…):   0%|          | 0.00/287M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00020-of-00(…):   0%|          | 0.00/287M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00021-of-00(…):   0%|          | 0.00/288M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00022-of-00(…):   0%|          | 0.00/282M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00023-of-00(…):   0%|          | 0.00/230M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00024-of-00(…):   0%|          | 0.00/231M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00025-of-00(…):   0%|          | 0.00/230M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00026-of-00(…):   0%|          | 0.00/231M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00027-of-00(…):   0%|          | 0.00/231M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00028-of-00(…):   0%|          | 0.00/231M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00029-of-00(…):   0%|          | 0.00/231M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00030-of-00(…):   0%|          | 0.00/230M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00031-of-00(…):   0%|          | 0.00/230M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00032-of-00(…):   0%|          | 0.00/230M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00033-of-00(…):   0%|          | 0.00/230M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00034-of-00(…):   0%|          | 0.00/231M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00035-of-00(…):   0%|          | 0.00/231M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00036-of-00(…):   0%|          | 0.00/230M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00037-of-00(…):   0%|          | 0.00/230M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00038-of-00(…):   0%|          | 0.00/231M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00039-of-00(…):   0%|          | 0.00/231M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00040-of-00(…):   0%|          | 0.00/231M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00041-of-00(…):   0%|          | 0.00/230M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00042-of-00(…):   0%|          | 0.00/230M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00043-of-00(…):   0%|          | 0.00/230M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00044-of-00(…):   0%|          | 0.00/231M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00045-of-00(…):   0%|          | 0.00/230M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00046-of-00(…):   0%|          | 0.00/231M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00047-of-00(…):   0%|          | 0.00/230M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00048-of-00(…):   0%|          | 0.00/231M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00049-of-00(…):   0%|          | 0.00/230M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00050-of-00(…):   0%|          | 0.00/231M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00051-of-00(…):   0%|          | 0.00/230M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00052-of-00(…):   0%|          | 0.00/231M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00053-of-00(…):   0%|          | 0.00/230M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00054-of-00(…):   0%|          | 0.00/231M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00055-of-00(…):   0%|          | 0.00/230M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00056-of-00(…):   0%|          | 0.00/231M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00057-of-00(…):   0%|          | 0.00/231M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00058-of-00(…):   0%|          | 0.00/230M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00059-of-00(…):   0%|          | 0.00/230M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00060-of-00(…):   0%|          | 0.00/231M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00061-of-00(…):   0%|          | 0.00/230M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00062-of-00(…):   0%|          | 0.00/231M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00063-of-00(…):   0%|          | 0.00/230M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00064-of-00(…):   0%|          | 0.00/231M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00065-of-00(…):   0%|          | 0.00/231M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00066-of-00(…):   0%|          | 0.00/230M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00067-of-00(…):   0%|          | 0.00/230M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00068-of-00(…):   0%|          | 0.00/231M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00069-of-00(…):   0%|          | 0.00/230M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00070-of-00(…):   0%|          | 0.00/230M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00071-of-00(…):   0%|          | 0.00/230M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00072-of-00(…):   0%|          | 0.00/231M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00073-of-00(…):   0%|          | 0.00/230M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00074-of-00(…):   0%|          | 0.00/230M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00075-of-00(…):   0%|          | 0.00/231M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00076-of-00(…):   0%|          | 0.00/231M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00077-of-00(…):   0%|          | 0.00/231M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00078-of-00(…):   0%|          | 0.00/230M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00079-of-00(…):   0%|          | 0.00/231M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00080-of-00(…):   0%|          | 0.00/231M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00081-of-00(…):   0%|          | 0.00/231M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00082-of-00(…):   0%|          | 0.00/231M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00083-of-00(…):   0%|          | 0.00/231M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00084-of-00(…):   0%|          | 0.00/231M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00085-of-00(…):   0%|          | 0.00/230M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00086-of-00(…):   0%|          | 0.00/230M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00087-of-00(…):   0%|          | 0.00/230M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00088-of-00(…):   0%|          | 0.00/230M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00089-of-00(…):   0%|          | 0.00/231M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00090-of-00(…):   0%|          | 0.00/230M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00091-of-00(…):   0%|          | 0.00/230M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00092-of-00(…):   0%|          | 0.00/231M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00093-of-00(…):   0%|          | 0.00/230M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00094-of-00(…):   0%|          | 0.00/231M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00095-of-00(…):   0%|          | 0.00/230M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00096-of-00(…):   0%|          | 0.00/230M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00097-of-00(…):   0%|          | 0.00/230M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00098-of-00(…):   0%|          | 0.00/231M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00099-of-00(…):   0%|          | 0.00/230M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00100-of-00(…):   0%|          | 0.00/230M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00101-of-00(…):   0%|          | 0.00/230M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00102-of-00(…):   0%|          | 0.00/230M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00103-of-00(…):   0%|          | 0.00/158M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00104-of-00(…):   0%|          | 0.00/150M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00105-of-00(…):   0%|          | 0.00/149M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00106-of-00(…):   0%|          | 0.00/150M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00107-of-00(…):   0%|          | 0.00/150M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00108-of-00(…):   0%|          | 0.00/150M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00109-of-00(…):   0%|          | 0.00/152M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00110-of-00(…):   0%|          | 0.00/150M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00111-of-00(…):   0%|          | 0.00/151M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_think-00112-of-00(…):   0%|          | 0.00/150M [00:00<?, ?B/s]

SFT/aya_dataset_Qwen3_32B_think-00000-of(…):   0%|          | 0.00/32.6M [00:00<?, ?B/s]

SFT/multi_turn_reasoning_if_think-00000-(…):   0%|          | 0.00/178M [00:00<?, ?B/s]

SFT/s1k_1.1_think-00000-of-00001.parquet:   0%|          | 0.00/12.3M [00:00<?, ?B/s]

SFT/smolagents_toolcalling_traces_think-(…):   0%|          | 0.00/81.8M [00:00<?, ?B/s]

SFT/smoltalk_everyday_convs_reasoning_Qw(…):   0%|          | 0.00/6.33M [00:00<?, ?B/s]

SFT/smoltalk_multilingual8_Qwen3_32B_thi(…):   0%|          | 0.00/264M [00:00<?, ?B/s]

SFT/smoltalk_multilingual8_Qwen3_32B_thi(…):   0%|          | 0.00/265M [00:00<?, ?B/s]

SFT/smoltalk_multilingual8_Qwen3_32B_thi(…):   0%|          | 0.00/265M [00:00<?, ?B/s]

SFT/smoltalk_multilingual8_Qwen3_32B_thi(…):   0%|          | 0.00/264M [00:00<?, ?B/s]

SFT/smoltalk_systemchats_Qwen3_32B_think(…):   0%|          | 0.00/64.9M [00:00<?, ?B/s]

SFT/table_gpt_Qwen3_32B_think-00000-of-0(…):   0%|          | 0.00/32.9M [00:00<?, ?B/s]

SFT/LongAlign_64k_context_lang_annotated(…):   0%|          | 0.00/199M [00:00<?, ?B/s]

SFT/Mixture_of_Thoughts_science_no_think(…):   0%|          | 0.00/63.5M [00:00<?, ?B/s]

SFT/OpenHermes_2.5_no_think-00000-of-000(…):   0%|          | 0.00/164M [00:00<?, ?B/s]

SFT/OpenHermes_2.5_no_think-00001-of-000(…):   0%|          | 0.00/159M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_no_think_no_think(…):   0%|          | 0.00/245M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_no_think_no_think(…):   0%|          | 0.00/121M [00:00<?, ?B/s]

SFT/OpenThoughts3_1.2M_no_think_no_think(…):   0%|          | 0.00/218M [00:00<?, ?B/s]

SFT/hermes_function_calling_v1_no_think-(…):   0%|          | 0.00/10.8M [00:00<?, ?B/s]

SFT/smoltalk_multilingual_8languages_lan(…):   0%|          | 0.00/158M [00:00<?, ?B/s]

SFT/smoltalk_multilingual_8languages_lan(…):   0%|          | 0.00/159M [00:00<?, ?B/s]

SFT/smoltalk_smollm3_everyday_conversati(…):   0%|          | 0.00/899k [00:00<?, ?B/s]

SFT/smoltalk_smollm3_explore_instruct_re(…):   0%|          | 0.00/5.34M [00:00<?, ?B/s]

SFT/smoltalk_smollm3_smol_magpie_ultra_n(…):   0%|          | 0.00/230M [00:00<?, ?B/s]

SFT/smoltalk_smollm3_smol_magpie_ultra_n(…):   0%|          | 0.00/230M [00:00<?, ?B/s]

SFT/smoltalk_smollm3_smol_magpie_ultra_n(…):   0%|          | 0.00/230M [00:00<?, ?B/s]

SFT/smoltalk_smollm3_smol_magpie_ultra_n(…):   0%|          | 0.00/230M [00:00<?, ?B/s]

SFT/smoltalk_smollm3_smol_magpie_ultra_n(…):   0%|          | 0.00/231M [00:00<?, ?B/s]

SFT/smoltalk_smollm3_smol_magpie_ultra_n(…):   0%|          | 0.00/231M [00:00<?, ?B/s]

SFT/smoltalk_smollm3_smol_rewrite_no_thi(…):   0%|          | 0.00/38.5M [00:00<?, ?B/s]

SFT/smoltalk_smollm3_smol_summarize_no_t(…):   0%|          | 0.00/117M [00:00<?, ?B/s]

SFT/smoltalk_smollm3_systemchats_30k_no_(…):   0%|          | 0.00/47.2M [00:00<?, ?B/s]

SFT/table_gpt_no_think-00000-of-00001.pa(…):   0%|          | 0.00/12.6M [00:00<?, ?B/s]

SFT/tulu_3_sft_personas_instruction_foll(…):   0%|          | 0.00/33.2M [00:00<?, ?B/s]

SFT/xlam_traces_no_think-00000-of-00001.(…):   0%|          | 0.00/30.6M [00:00<?, ?B/s]

Generating LongAlign_64k_Qwen3_32B_yarn_131k_think split:   0%|          | 0/7526 [00:00<?, ? examples/s]

Generating OpenThoughts3_1.2M_think split:   0%|          | 0/1133524 [00:00<?, ? examples/s]

Generating aya_dataset_Qwen3_32B_think split:   0%|          | 0/15222 [00:00<?, ? examples/s]

Generating multi_turn_reasoning_if_think split:   0%|          | 0/28217 [00:00<?, ? examples/s]

Generating s1k_1.1_think split:   0%|          | 0/835 [00:00<?, ? examples/s]

Generating smolagents_toolcalling_traces_think split:   0%|          | 0/9079 [00:00<?, ? examples/s]

Generating smoltalk_everyday_convs_reasoning_Qwen3_32B_think split:   0%|          | 0/2057 [00:00<?, ? exampl…

Generating smoltalk_multilingual8_Qwen3_32B_think split:   0%|          | 0/244736 [00:00<?, ? examples/s]

Generating smoltalk_systemchats_Qwen3_32B_think split:   0%|          | 0/27436 [00:00<?, ? examples/s]

Generating table_gpt_Qwen3_32B_think split:   0%|          | 0/13201 [00:00<?, ? examples/s]

Generating LongAlign_64k_context_lang_annotated_lang_6_no_think split:   0%|          | 0/6249 [00:00<?, ? exa…

Generating Mixture_of_Thoughts_science_no_think split:   0%|          | 0/86110 [00:00<?, ? examples/s]

Generating OpenHermes_2.5_no_think split:   0%|          | 0/384900 [00:00<?, ? examples/s]

Generating OpenThoughts3_1.2M_no_think_no_think split:   0%|          | 0/435193 [00:00<?, ? examples/s]

Generating hermes_function_calling_v1_no_think split:   0%|          | 0/8961 [00:00<?, ? examples/s]

Generating smoltalk_multilingual_8languages_lang_5_no_think split:   0%|          | 0/254047 [00:00<?, ? examp…

Generating smoltalk_smollm3_everyday_conversations_no_think split:   0%|          | 0/2260 [00:00<?, ? example…

Generating smoltalk_smollm3_explore_instruct_rewriting_no_think split:   0%|          | 0/30391 [00:00<?, ? ex…

Generating smoltalk_smollm3_smol_magpie_ultra_no_think split:   0%|          | 0/406843 [00:00<?, ? examples/s…

Generating smoltalk_smollm3_smol_rewrite_no_think split:   0%|          | 0/53262 [00:00<?, ? examples/s]

Generating smoltalk_smollm3_smol_summarize_no_think split:   0%|          | 0/96061 [00:00<?, ? examples/s]

Generating smoltalk_smollm3_systemchats_30k_no_think split:   0%|          | 0/33997 [00:00<?, ? examples/s]

Generating table_gpt_no_think split:   0%|          | 0/13203 [00:00<?, ? examples/s]

Generating tulu_3_sft_personas_instruction_following_no_think split:   0%|          | 0/29970 [00:00<?, ? exam…

Generating xlam_traces_no_think split:   0%|          | 0/59962 [00:00<?, ? examples/s]

Loading dataset shards:   0%|          | 0/105 [00:00<?, ?it/s]

Total splits: 25
Available splits: ['LongAlign_64k_Qwen3_32B_yarn_131k_think', 'OpenThoughts3_1.2M_think', 'aya_dataset_Qwen3_32B_think', 'multi_turn_reasoning_if_think', 's1k_1.1_think', 'smolagents_toolcalling_traces_think', 'smoltalk_everyday_convs_reasoning_Qwen3_32B_think', 'smoltalk_multilingual8_Qwen3_32B_think', 'smoltalk_systemchats_Qwen3_32B_think', 'table_gpt_Qwen3_32B_think', 'LongAlign_64k_context_lang_annotated_lang_6_no_think', 'Mixture_of_Thoughts_science_no_think', 'OpenHermes_2.5_no_think', 'OpenThoughts3_1.2M_no_think_no_think', 'hermes_function_calling_v1_no_think', 'smoltalk_multilingual_8languages_lang_5_no_think', 'smoltalk_smollm3_everyday_conversations_no_think', 'smoltalk_smollm3_explore_instruct_rewriting_no_think', 'smoltalk_smollm3_smol_magpie_ultra_no_think', 'smoltalk_smollm3_smol_rewrite_no_think', 'smoltalk_smollm3_smol_summarize_no_think', 'smoltalk_smollm3_systemchats_30k_no_think', 'table_gpt_no_think', 'tulu_3_sft_personas_instruction_following_no_think', 'xlam_traces_no_think']
Number of total rows: 3383242
Dataset structure: DatasetDict({
    LongAlign_64k_Qwen3_32B_yarn_131k_think: Dataset({
        features: ['messages', 'chat_template_kwargs', 'source'],
        num_rows: 7526
    })
    OpenThoughts3_1.2M_think: Dataset({
        features: ['messages', 'chat_template_kwargs', 'source'],
        num_rows: 1133524
    })
    aya_dataset_Qwen3_32B_think: Dataset({
        features: ['messages', 'chat_template_kwargs', 'source'],
        num_rows: 15222
    })
    multi_turn_reasoning_if_think: Dataset({
        features: ['messages', 'chat_template_kwargs', 'source'],
        num_rows: 28217
    })
    s1k_1.1_think: Dataset({
        features: ['messages', 'chat_template_kwargs', 'source'],
        num_rows: 835
    })
    smolagents_toolcalling_traces_think: Dataset({
        features: ['messages', 'chat_template_kwargs', 'source'],
        num_rows: 9079
    })
    smoltalk_everyday_convs_reasoning_Qwen3_32B_think: Dataset({
        features: ['messages', 'chat_template_kwargs', 'source'],
        num_rows: 2057
    })
    smoltalk_multilingual8_Qwen3_32B_think: Dataset({
        features: ['messages', 'chat_template_kwargs', 'source'],
        num_rows: 244736
    })
    smoltalk_systemchats_Qwen3_32B_think: Dataset({
        features: ['messages', 'chat_template_kwargs', 'source'],
        num_rows: 27436
    })
    table_gpt_Qwen3_32B_think: Dataset({
        features: ['messages', 'chat_template_kwargs', 'source'],
        num_rows: 13201
    })
    LongAlign_64k_context_lang_annotated_lang_6_no_think: Dataset({
        features: ['messages', 'chat_template_kwargs', 'source'],
        num_rows: 6249
    })
    Mixture_of_Thoughts_science_no_think: Dataset({
        features: ['messages', 'chat_template_kwargs', 'source'],
        num_rows: 86110
    })
    OpenHermes_2.5_no_think: Dataset({
        features: ['messages', 'chat_template_kwargs', 'source'],
        num_rows: 384900
    })
    OpenThoughts3_1.2M_no_think_no_think: Dataset({
        features: ['messages', 'chat_template_kwargs', 'source'],
        num_rows: 435193
    })
    hermes_function_calling_v1_no_think: Dataset({
        features: ['messages', 'chat_template_kwargs', 'source'],
        num_rows: 8961
    })
    smoltalk_multilingual_8languages_lang_5_no_think: Dataset({
        features: ['messages', 'chat_template_kwargs', 'source'],
        num_rows: 254047
    })
    smoltalk_smollm3_everyday_conversations_no_think: Dataset({
        features: ['messages', 'chat_template_kwargs', 'source'],
        num_rows: 2260
    })
    smoltalk_smollm3_explore_instruct_rewriting_no_think: Dataset({
        features: ['messages', 'chat_template_kwargs', 'source'],
        num_rows: 30391
    })
    smoltalk_smollm3_smol_magpie_ultra_no_think: Dataset({
        features: ['messages', 'chat_template_kwargs', 'source'],
        num_rows: 406843
    })
    smoltalk_smollm3_smol_rewrite_no_think: Dataset({
        features: ['messages', 'chat_template_kwargs', 'source'],
        num_rows: 53262
    })
    smoltalk_smollm3_smol_summarize_no_think: Dataset({
        features: ['messages', 'chat_template_kwargs', 'source'],
        num_rows: 96061
    })
    smoltalk_smollm3_systemchats_30k_no_think: Dataset({
        features: ['messages', 'chat_template_kwargs', 'source'],
        num_rows: 33997
    })
    table_gpt_no_think: Dataset({
        features: ['messages', 'chat_template_kwargs', 'source'],
        num_rows: 13203
    })
    tulu_3_sft_personas_instruction_following_no_think: Dataset({
        features: ['messages', 'chat_template_kwargs', 'source'],
        num_rows: 29970
    })
    xlam_traces_no_think: Dataset({
        features: ['messages', 'chat_template_kwargs', 'source'],
        num_rows: 59962
    })
})
NUmber of rows in this training split:  2057

In [9]:
print(f"Processed example: {train_dataset[0]}")

Processed example: {'messages': [{'content': 'Hi there', 'role': 'user'}, {'content': '<think>\nOkay, the user sent "Hi there". That\'s a friendly greeting. I should respond in a welcoming way. Let me check the guidelines. I need to be helpful, keep the conversation going, and maybe ask how I can assist them. Let me make sure the tone is warm and approachable. Alright, something like "Hello! How can I assist you today?" That should work. Let me confirm there\'s no typo and it\'s in a natural, conversational style.\n</think>\n\nHello! How can I assist you today?', 'role': 'assistant'}, {'content': "I'm looking for a healthy breakfast idea. What's a good option?", 'role': 'user'}, {'content': "<think>\nOkay, the user is asking for a healthy breakfast idea. Let me think about what makes a breakfast healthy. It should be balanced, providing a mix of nutrients like protein, fiber, healthy fats, and some carbs. Let me brainstorm some options.\n\nMaybe start with a classic like avocado toast. It's popular and has good fats and fiber. Adding an egg or Greek yogurt could boost the protein. Oh, and maybe some veggies on top for extra nutrients. That could work.\n\nAnother option could be a smoothie. Smoothies are quick and can pack a lot of nutrients. Using spinach, banana, berries, and a protein powder or Greek yogurt would be good. Maybe add some nut butter for healthy fats. That's a solid choice too.\n\nOatmeal is another staple. Overnight oats are convenient. Mixing oats with milk, chia seeds, and fruits. Maybe add some nuts or seeds for crunch. It's high in fiber and can be customized.\n\nWhat about a breakfast bowl with quinoa or another grain? Topped with fruits, nuts, and a drizzle of honey or nut butter. That's another balanced option.\n\nI should also consider dietary restrictions. Maybe mention alternatives for those who are vegan, gluten-free, etc. For example, using almond milk instead of dairy in the smoothie or choosing gluten-free oats.\n\nPortion sizes and preparation time might be important too. The user might be looking for something quick or something they can prep ahead. The avocado toast is quick, the overnight oats can be prepped the night before.\n\nIncluding a variety of options gives the user choices based on their preferences and time. Let me structure the response with a couple of options, each with ingredients and preparation steps. Also, highlight the nutritional benefits of each. Make sure to keep the tone friendly and helpful.\n</think>\n\nHere’s a quick and nutritious breakfast idea that’s easy to customize:\n\n### **Avocado Toast with a Twist**  \n**Ingredients:**  \n- 1 slice whole-grain or sourdough bread (toasted)  \n- ½ ripe avocado, mashed  \n- 1 poached or scrambled egg (or a dollop of Greek yogurt for a vegan option)  \n- Sprinkle of chili flakes, black pepper, and a pinch of sea salt  \n- Optional toppings: cherry tomatoes, microgreens, or a drizzle of olive oil  \n\n**Why it’s healthy:**  \n- **Whole grains** provide fiber for sustained energy.  \n- **Avocado** adds healthy fats and potassium.  \n- **Eggs/Greek yogurt** offer high-quality protein to keep you full.  \n- **Spices** add flavor without extra calories.  \n\n---\n\n### **Protein-Packed Smoothie Bowl**  \n**Ingredients:**  \n- 1 frozen banana  \n- ½ cup frozen berries (blueberries, strawberries, etc.)  \n- ½ cup unsweetened almond milk (or any milk of choice)  \n- 1 scoop vanilla protein powder (or ¼ cup Greek yogurt)  \n- 1 tbsp chia seeds or flaxseeds  \n- Toppings: sliced fruit, granola, nuts, or cacao nibs  \n\n**Blend it up**, pour into a bowl, and add toppings.  \n\n**Why it’s healthy:**  \n- **Fiber and antioxidants** from fruits and seeds.  \n- **Protein** supports muscle repair and satiety.  \n- **Healthy fats** from seeds or nut toppings.  \n\n---\n\n### **Overnight Oats (Make-Ahead Option)**  \n**Ingredients:**  \n- ½ cup rolled oats  \n- ½ cup milk (dairy or plant-based)  \n- 1 tbsp nut butter (peanut, almond, etc.)  \n- 1 tsp honey or maple syrup  \n- ½ tsp chia seeds  \n- Toppings: fresh fruit, cinnamon, or a sprinkle of granola  \n\n**Instructions:**  \nMix all ingredients in a jar, refrigerate overnight, and enjoy cold or at room temperature.  \n\n**Why it’s healthy:**  \n- **Slow-digesting carbs** for steady energy.  \n- **Chia seeds** add omega-3s and fiber.  \n- **Nut butter** provides protein and healthy fats.  \n\n---\n\nLet me know if you’d like more ideas or adjustments for dietary needs (e.g., vegan, gluten-free, low-carb)! 😊", 'role': 'assistant'}], 'chat_template_kwargs': {'custom_instructions': '', 'enable_thinking': True, 'python_tools': [], 'xml_tools': []}, 'source': 'smoltalk-everyday-convs-reasoning-Qwen3-32B'}

In [10]:
# Prepare the dataset for SFT
def format_chat_template(example):
    """Format the messages using the chat template"""
    if "messages" in example:
        # SmolTalk2 format
        messages = example["messages"]
    else:
        # Custom format - adapt as needed
        messages = [
            {"role": "user", "content": example["instruction"]},
            {"role": "assistant", "content": example["response"]}
        ]
    
    # Apply chat template
    text = instruct_tokenizer.apply_chat_template(
        messages, 
        tokenize=False,
        add_generation_prompt=False
    )
    return {"text": text}

# Apply formatting
formatted_dataset = train_dataset.map(format_chat_template, batched=True)
formatted_dataset = formatted_dataset.remove_columns(
    [col for col in formatted_dataset.column_names if col != "text"]
)
print(f"Formatted example: {formatted_dataset[0]['text']}...")

Map:   0%|          | 0/2000 [00:00<?, ? examples/s]

Formatted example: <|im_start|>system
## Metadata

Knowledge Cutoff Date: June 2025
Today Date: 01 February 2026
Reasoning Mode: /think

## Custom Instructions

You are a helpful AI assistant named SmolLM, trained by Hugging Face. Your role as an assistant involves thoroughly exploring questions through a systematic thinking process before providing the final precise and accurate solutions. This requires engaging in a comprehensive cycle of analysis, summarizing, exploration, reassessment, reflection, backtracking, and iteration to develop well-considered thinking process. Please structure your response into two main sections: Thought and Solution using the specified format: <think> Thought section </think> Solution section. In the Thought section, detail your reasoning process in steps. Each step should include detailed considerations such as analysing questions, summarizing relevant findings, brainstorming new ideas, verifying the accuracy of the current steps, refining any errors, and revisiting previous steps. In the Solution section, based on various attempts, explorations, and reflections from the Thought section, systematically present the final solution that you deem correct. The Solution section should be logical, accurate, and concise and detail necessary steps needed to reach the conclusion.

<|im_start|>user
Hi there<|im_end|>
<|im_start|>assistant
<think>
Okay, the user sent "Hi there". That's a friendly greeting. I should respond in a welcoming way. Let me check the guidelines. I need to be helpful, keep the conversation going, and maybe ask how I can assist them. Let me make sure the tone is warm and approachable. Alright, something like "Hello! How can I assist you today?" That should work. Let me confirm there's no typo and it's in a natural, conversational style.
</think>

Hello! How can I assist you today?<|im_end|>
<|im_start|>user
I'm looking for a healthy breakfast idea. What's a good option?<|im_end|>
<|im_start|>assistant
<think>
Okay, the user is asking for a healthy breakfast idea. Let me think about what makes a breakfast healthy. It should be balanced, providing a mix of nutrients like protein, fiber, healthy fats, and some carbs. Let me brainstorm some options.

Maybe start with a classic like avocado toast. It's popular and has good fats and fiber. Adding an egg or Greek yogurt could boost the protein. Oh, and maybe some veggies on top for extra nutrients. That could work.

Another option could be a smoothie. Smoothies are quick and can pack a lot of nutrients. Using spinach, banana, berries, and a protein powder or Greek yogurt would be good. Maybe add some nut butter for healthy fats. That's a solid choice too.

Oatmeal is another staple. Overnight oats are convenient. Mixing oats with milk, chia seeds, and fruits. Maybe add some nuts or seeds for crunch. It's high in fiber and can be customized.

What about a breakfast bowl with quinoa or another grain? Topped with fruits, nuts, and a drizzle of honey or nut butter. That's another balanced option.

I should also consider dietary restrictions. Maybe mention alternatives for those who are vegan, gluten-free, etc. For example, using almond milk instead of dairy in the smoothie or choosing gluten-free oats.

Portion sizes and preparation time might be important too. The user might be looking for something quick or something they can prep ahead. The avocado toast is quick, the overnight oats can be prepped the night before.

Including a variety of options gives the user choices based on their preferences and time. Let me structure the response with a couple of options, each with ingredients and preparation steps. Also, highlight the nutritional benefits of each. Make sure to keep the tone friendly and helpful.
</think>

Here’s a quick and nutritious breakfast idea that’s easy to customize:

### **Avocado Toast with a Twist**
**Ingredients:**
- 1 slice whole-grain or sourdough bread (toasted)
- ½ ripe avocado, mashed
- 1 poached or scrambled egg (or a dollop of Greek yogurt for a vegan option)
- Sprinkle of chili flakes, black pepper, and a pinch of sea salt
- Optional toppings: cherry tomatoes, microgreens, or a drizzle of olive oil

**Why it’s healthy:**
- **Whole grains** provide fiber for sustained energy.
- **Avocado** adds healthy fats and potassium.
- **Eggs/Greek yogurt** offer high-quality protein to keep you full.
- **Spices** add flavor without extra calories.

---

### **Protein-Packed Smoothie Bowl**
**Ingredients:**
- 1 frozen banana
- ½ cup frozen berries (blueberries, strawberries, etc.)
- ½ cup unsweetened almond milk (or any milk of choice)
- 1 scoop vanilla protein powder (or ¼ cup Greek yogurt)
- 1 tbsp chia seeds or flaxseeds
- Toppings: sliced fruit, granola, nuts, or cacao nibs

**Blend it up**, pour into a bowl, and add toppings.

**Why it’s healthy:**
- **Fiber and antioxidants** from fruits and seeds.
- **Protein** supports muscle repair and satiety.
- **Healthy fats** from seeds or nut toppings.

---

### **Overnight Oats (Make-Ahead Option)**
**Ingredients:**
- ½ cup rolled oats
- ½ cup milk (dairy or plant-based)
- 1 tbsp nut butter (peanut, almond, etc.)
- 1 tsp honey or maple syrup
- ½ tsp chia seeds
- Toppings: fresh fruit, cinnamon, or a sprinkle of granola

**Instructions:**
Mix all ingredients in a jar, refrigerate overnight, and enjoy cold or at room temperature.

**Why it’s healthy:**
- **Slow-digesting carbs** for steady energy.
- **Chia seeds** add omega-3s and fiber.
- **Nut butter** provides protein and healthy fats.

---

Let me know if you’d like more ideas or adjustments for dietary needs (e.g., vegan, gluten-free, low-carb)! 😊<|im_end|>
...

### LoRA SFT with TRL + SmolLM3

In [11]:
# Import required libraries for fine-tuning
from transformers import AutoModelForCausalLM, AutoTokenizer, TrainingArguments
from trl import SFTTrainer, SFTConfig
import torch

# Load SmolLM3 model for fine-tuning
raw_model_name = "HuggingFaceTB/SmolLM3-3B"
# raw_model_name = "HuggingFaceTB/SmolLM3-3B-base"
lora_instruct_model_name = "SmolLM3-Custom-SFT"

print(f"Loading {raw_model_name}...")
raw_model = AutoModelForCausalLM.from_pretrained(
    raw_model_name,
    dtype=torch.float16,  # Use float16 for memory efficiency
    device_map="auto",
    trust_remote_code=True,
)

raw_tokenizer = AutoTokenizer.from_pretrained(raw_model_name)

print(f"Model loaded! Parameters: {raw_model.num_parameters():,}")
print("Check special tokens:", raw_tokenizer.bos_token, raw_tokenizer.eos_token, raw_tokenizer.pad_token)

Loading HuggingFaceTB/SmolLM3-3B...

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Model loaded! Parameters: 3,075,098,624
Check special tokens: None <|im_end|> <|im_end|>

In [ ]:
from peft import LoraConfig, get_peft_model

# LoRA config
peft_config = LoraConfig(
    r=8,
    lora_alpha=16,
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
    target_modules=[
        "q_proj",
        "k_proj",
        "v_proj",
        "o_proj",
        "gate_proj",
        "up_proj",
        "down_proj",
    ]
)

# Configure training parameters
training_config = SFTConfig(
    # Model and data
    output_dir=f"./{lora_instruct_model_name}",
    dataset_text_field="text",
    max_length=2048,
    # assistant_only_loss=True, # added (only train on the assistant generation)

    # Training hyperparameters
    per_device_train_batch_size=2,  # Adjust based on your GPU memory
    gradient_accumulation_steps=2,
    learning_rate=1e-4,
    num_train_epochs=1,  # Start with 1 epoch
    max_steps=1000,  # Limit steps for demo

    # Optimization
    warmup_steps=50,
    weight_decay=0.01,
    optim="adamw_torch",

    # Logging and saving
    logging_steps=10,
    save_steps=100,
    eval_steps=100,
    save_total_limit=2,

    # Memory optimization
    dataloader_num_workers=0,
    group_by_length=True,  # Group similar length sequences
    report_to = "none",

    # # Hugging Face Hub integration
    # push_to_hub=False,  # Set to True to upload to Hub
    # hub_model_id=f"your-username/{new_model_name}",

    # # Experiment tracking
    # report_to=["trackio"],  # Use trackio for experiment tracking
    # run_name=f"{new_model_name}-training",
)

print("Training configuration set!")
print(f"Effective batch size: {training_config.per_device_train_batch_size * training_config.gradient_accumulation_steps}")

Training configuration set!
Effective batch size: 4

In [13]:
# Create SFTTrainer with LoRA enabled

# lora_instruct_model = get_peft_model(raw_model, peft_config) # way-1
# lora_instruct_model.print_trainable_parameters() # way-1

lora_trainer = SFTTrainer(
    # model=lora_instruct_model, # way-1
    model = raw_model, # way-2
    # train_dataset=formatted_dataset,  # base_model not with chat_template; dataset with a "text" field or messages + dataset_text_field in config
    train_dataset = train_dataset, # work with instruct_model, default with chat_template;
    args=training_config,
    peft_config=peft_config,  # << enable LoRA: warp peft_config # way-2
)

print("Starting LoRA training…")
lora_trainer.train()

# lora_instruct_model.save_pretrained(lora_instruct_model_name) # way-1-1
# model = PeftModel.from_pretrained(raw_model, lora_instruct_model_name) # way-1-1

Tokenizing train dataset:   0%|          | 0/2000 [00:00<?, ? examples/s]

Truncating train dataset:   0%|          | 0/2000 [00:00<?, ? examples/s]

The model is already on multiple devices. Skipping the move to device specified in `args`.
The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 128012}.

Starting LoRA training…

TrainOutput(global_step=1000, training_loss=0.6811862144470214, metrics={'train_runtime': 1589.2938, 'train_samples_per_second': 2.517, 'train_steps_per_second': 0.629, 'total_flos': 1.0201008345029837e+17, 'train_loss': 0.6811862144470214})

In [14]:
lora_trainer.save_model() # saved the trained model wrapped with lora parameters
model = AutoModelForCausalLM.from_pretrained(lora_instruct_model_name, device_map="auto")

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

In [15]:
test_prompt = "How to learn Agentic AI?"
# Prepare the prompt for instruct model (with chat template)
instruct_messages = [
    {"role": "system", "content": "/think"},
    {"role": "user", "content": test_prompt}
]
instruct_formatted = instruct_tokenizer.apply_chat_template(
    instruct_messages, tokenize=False, add_generation_prompt=True
)
instruct_inputs = instruct_tokenizer(instruct_formatted, return_tensors="pt").to(device)

# Generate responses

with torch.no_grad():
    instruct_outputs = model.generate(
        **instruct_inputs,
        max_new_tokens=1024,
        temperature=0.7,
        do_sample=True,
        pad_token_id=instruct_tokenizer.eos_token_id,
    )
    instruct_response = instruct_tokenizer.decode(
        instruct_outputs[0], skip_special_tokens=False
    )
    # Extract only the assistant's response
    assistant_start = instruct_response.find("<|im_start|>assistant\n") + len(
        "<|im_start|>assistant\n"
    )
    assistant_response = instruct_response[assistant_start:]
    print(assistant_response)

<think>
Okay, the user is asking how to learn Agentic AI. First, I need to define what Agentic AI is. From what I remember, Agentic AI refers to AI systems that have agency, meaning they can make decisions autonomously and take actions based on their goals. They have a sense of self, intentionality, and the ability to reason and adapt.

So, the user probably wants to understand the fundamentals of this field. They might be a student, a researcher, or someone interested in the intersection of AI and ethics. I should start by explaining the key concepts: autonomy, intentionality, self-awareness, and decision-making processes.

Next, I should outline the core principles of Agentic AI. These include the need for self-modeling, goal representation, and interaction with the environment. Self-modeling means the AI can reflect on its own behavior and adjust accordingly. Goal representation is about defining objectives and adjusting them as needed. Interaction with the environment involves sensing the surroundings and responding appropriately.

Then, I should mention the components of an Agentic AI system. These might include a self-model, goal system, action planner, and a decision-maker. Each component has its own subcomponents and algorithms. For example, the self-model might use reinforcement learning to update its internal state.

I should also touch on the challenges in developing Agentic AI. These include ensuring safety, preventing unintended consequences, and addressing the ethics of autonomous decision-making. It's important to highlight the ethical considerations, like transparency and accountability, to reassure the user that the field isn't just about technology but also about responsibility.

Next, resources for learning. I need to list academic papers, books, and online courses. For example, "Agentic AI: The Future of Artificial Intelligence" by a well-known author might be a good starting point. Online courses on Coursera or edX could provide structured learning. Also, mentioning conferences like AAAI or ICML might be useful for staying updated.

Practical steps for learning would involve starting with foundational AI concepts, then moving to Agentic AI specific topics. Recommending projects or competitions where they can apply their knowledge, like the Autonomous Robot Competition or Kaggle challenges, could be helpful.

I should also consider potential follow-up questions. For example, how to transition from traditional AI to Agentic AI, or how to handle the computational complexity of self-aware systems. Maybe suggest reading the literature on reinforcement learning and multi-agent systems, as those are foundational for Agentic AI.

Wait, I need to make sure I'm not missing any key points. The user might also be interested in the difference between Agentic AI and traditional AI. Emphasizing that Agentic AI is about self-awareness and autonomy, while traditional AI is more about pattern recognition and task execution. Also, mentioning examples of current research or real-world applications could make the topic more tangible, like self-driving cars or autonomous drones.

I should structure the answer in a logical flow: start with an overview, then key concepts, components, challenges, resources, and practical steps. Using clear headings and bullet points would make it easier to follow. Also, ensuring that the explanation is accessible to someone who might not have a background in AI, but still covers the necessary technical details.

Finally, I need to check if there are any common misconceptions about Agentic AI. For example, some might think it's about human-like consciousness, but it's more about decision-making autonomy. Clarifying that could help the user understand the scope of the field better.
</think>

Learning Agentic AI (Artificial General Intelligence with agency) is a complex and interdisciplinary field that combines AI, philosophy, ethics, and cognitive science. Here's a structured approach to help you navigate this topic:

---

### **1. Understand the Foundations**
Agentic AI refers to systems that exhibit **agency**, meaning they can:
- **Self-reflect**: Understand their internal state and behavior.
- **Act autonomously**: Make decisions and take actions to achieve goals.
- **Adapt**: Learn from experiences and adjust their strategies.

**Key Concepts to Grasp**:
- **Autonomy vs. Human-like Intelligence**: Agentic AI is not about replicating human consciousness but enabling machines to act independently with purpose.
- **Self-Modeling**: The ability to model one’s internal state and behavior (e.g., using RL to update beliefs).
- **Goal Representation**: Defining and updating objectives (e.g., reinforcement learning, planning).
- **Interaction with the Environment**: Sensing and responding to the world (e.g., sensorimotor cycles).

---

### **2. Core Components of an Agentic AI System**
An Agentic AI typically includes:
1. **Self-Model**: A representation of the AI’s internal state (e.g., beliefs, intentions, and past actions).
2. **Goal System**: Defines objectives and updates them based on feedback.
3. **Action Planner**: Generates actions to achieve goals (e.g., decision-theory or planning algorithms).
4. **Decision-Maker**: Combines internal

### Full Parameter Supervised Fine-tuning

In [16]:
# Initialize the SFTTrainer
trainer = SFTTrainer(
    model=model,
    args=training_config,
    # train_dataset = formatted_dataset,
    train_dataset=train_dataset,
)

# Start training!
print("\n=== STARTING TRAINING ===")
trainer.train()

# Save the model
trainer.save_model()
print(f"Model saved to {training_config.output_dir}")

The model is already on multiple devices. Skipping the move to device specified in `args`.
The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 128012}.

=== STARTING TRAINING ===

Model saved to ./SmolLM3-Custom-SFT

Acknowledgement: https://huggingface.co/learn/smol-course/unit1/4